apiVersion: notification.halo.run/v1alpha1
kind: NotificationTemplate
metadata:
  name: template-lottery-verification-code
spec:
  reasonSelector:
    reasonType: lottery-verification-code
    language: default
  template:
    title: "【抽奖验证码】[[${code}]]"
    rawBody: |
      您的抽奖验证码是：[[${code}]]

      验证码有效期为 [[${expireMinutes}]] 分钟，请尽快使用。

      如果这不是您的操作，请忽略此邮件。
    htmlBody: |
      <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 500px; margin: 0 auto; padding: 20px;">
        <p style="color: #333; font-size: 15px; margin: 0 0 16px;">您正在参与抽奖活动，验证码为：</p>
        <div style="background: #f5f5f5; padding: 16px; border-radius: 6px; text-align: center; margin: 16px 0;">
          <span style="font-size: 28px; font-weight: 600; letter-spacing: 6px; color: #333;">[[${code}]]</span>
        </div>
        <p style="color: #666; font-size: 13px; margin: 16px 0 0;">验证码 [[${expireMinutes}]] 分钟内有效。如非本人操作，请忽略。</p>
      </div>
